services:
  sockerless-backend:
    build:
      context: ../..
      dockerfile: smoke-tests/gitlab/Dockerfile.backend-cloudrun
    command: []
    environment:
      CLOUD: gcp
      BACKEND_ADDR: ":9100"
